language: node_js
node_js:
- 10.6.0
install:
- npm install
cache:
  directories:
  - node_modules
script:
- npm run build && npm run ci-deploy
env:
  global:
  - secure: abc
  - secure: G0P2EDEXJJzJ6Pyq77YQ7ISA9uO19ZPUG3Fffcpz+4V3z7jUtuGA5DqpDXmIlZT9/n4ovNqxvfiu9KuZ7sn1CBgHiV+Y7Rzk1wg73Nsdo+oXzGKMJL6TFzPty4JQegOCO4VANvM3XJuirD/zPNWCtw8B596N5pPV4PHCyDG73PxdR3kgeSIXH3f/IRlgtjBCDjX07FTmsBGHsTiE3XaFUPNp/KewOCfb3a3rUj1mUXZCt5xa0EDqWu3WnnX8/Gvcst2+j77cqJUr/FLWJT9DgdxgQDvWLubSnrLRqDjH6tOEvm4kesMPBXDV32L8EbqHA7xfQO5d8Ha6K11JEz4ezROKcla7mdVepVhfAw3u0OLd1DPGmX0jNV0N5CQTdi2x/NyJiM+BCQEjNYBt4nIRMQWE+fu+kt8ByBkhGbYBzUff8M3blFfoosoqbF19vXQ+QiIDRZvpYpKl0LcTR2lUi2o0wznJt6ai1Mh10ACHV97sKDs9jeS6SFk88KrjPoucSGYip0poWyUwGy2yuv8SWN6G6n1KxfH8CLhK74Y4DKWgMSjMT7xA7+O5xU5KPSixKkPyga/pyKYQVamCvZg5eTac9hiiGzp5jvRGzzk0MZ5EZIuVUoGSr/pkFVUFE9r6egra00/pAQa/ERA72k8EL4OvWptB4kp3S/f0XoKILpM=
  - secure: Uh+eR6R51rSFiGEQC4pMSsOhxwn4DX201CI7Cg9fTCkfdSDdDRLB4g8uEldVkMx9c7xHLwyTGJgS2WCTRkb119WD44rt2er2SHXNfUm6e1cJ7sxWr5m71FR+X9dAqIMlVmO8MGfuM9NIpVMMa/5nfrr+5z0ogF8hfxLDjHavBYHk7fnN72AGLBLDkBCD+RMc/LIwPLufmgF8j4NyOsrwYPeN2S8GaOPi755Q9Kagy2ZRwvGsxQP2+3V3SldaSvMoBxMEgy1lrlEO2iw4OD+tcCC+gOblaw0foay1W5uGFULyknU3jMFR4vzN/+cq7a5WwvXDtRi/oT/4qpQuzhTxdXk+LEK73U6OL2rZKVCPyq3698cyhlmG0LIuMH5bykmwUS9NwzPYwp6aaiXuMNRJJriEMo+gAVOhsj4nZPqUGQEYTBB2CM5BwzWVAaisWorxT8jSqtscnuIlJF3zWuem3sLn0xf+YjwcQn9T5+MuVSr8Mhm9hbPnqDK1CVuN5lXYqTcL5I+v3aiqSxbYWtVN7QGpko2dJG1cavCvwaBmv2V9i+j7tocca7QZ6PMp0NrxCBaJOYEY6fp0Kh+NTT2EU9QCq7wPUHnZmAe/dWcwe1+iLO1cEKOIgHTakyL7n3zhQoc5pSoVxsTeHfoBeB55FCnbMIH2wYHJCWMqfxdhUtQ=
