language: node_js
node_js:
- 10.6.0
install:
- npm install
cache:
  directories:
  - node_modules
script:
- npm run build && npm run ci-deploy
env:
  global:
  - secure: l1usgPuIp9cZStY1U9r9gww7DBxSNoCCu9NB+wKvkLA8Z1dYnoXxfUgP+q6p/bB+IAp4xfKeWqKurlwnWKv/4ZA4tU8lQ5BPAyjurSC1upIsEAXBfEXyHMckG/d1Q47KkYNHOgzDPc2MT5HJSwR8aeuTB9jqZ6HM6yoK0S1ZM8hX8Jql9DAP7qAfkvtXPpoykP4IRkXSSo02MTnmwMztwuLrTHztf+1pQsd6wb8E7LjVvNnvmX/uh6ZhVhUzDLygSAriDdZk2FMGb1MIEtDRwWGL6SDigvtP8CRU2uqhEhcJF9MCeQ5zUf1EBtWVHS0dAs08D0BxQX3s6D3SQAhV2ofn6D6PUYLk3u/mQ9Ow7zceUEcRq1yspAl3NNSugFDcJZ1PMR6YncLOyd1tK6abg1ikeaQQU9CloUBb0/zdJ4PKJvaOpzqQwUs1Tm3bUtr4OZk4Ow0dILfVwYQoQPHsOLtJpYIE0cXBYUZoTN9J9IpiVSCrD+385q7eQbpxaSpu8W2ykQjKhlJpaouCqCc/vzp1PGIRopeUOrKHzMdoPlPdGuBz5L648Yyb8KuikLGowdbo6/Lb4SPpwCmpRxOfcXVJ/Ug9xskYcCYIwQ3NYhA5SEI67l3hFdPCITwa3joL7zjcecaIFeqOjhsAY0x9b/K4+Q1jQ+wXx05p2rVDsys=
  - secure: lnxpjV9EusUS/nsDI39pkD8EXYyaoyKvJceqdKf7C2aHjUEJhlMFBxqtQH0pJfZqVVzTX6yyVViOv2p7ylnJuHcm5i7cE7JKWMA3DpZj7h2cOcKdrlHHLQStyMOxBvlTEiqOtBFPtFj+7loL+Vp+526WOgGEMef6jD3Ne27HkAS8neTaXZXLsFTbNaWMdVfOU7dLV+pDv9HKB4W/Uu+7wCV6HijvXYw2C2z6EVVnvAFuPltG5+igF0zGJX/Ll1zbZ6vi56kMOhHQ0AxVhh84MKsFKjVYnWb+LQIm6xT+uMU9F6wtNCzTEklKnmZKKPTmnlv0zzmRiuZ7tDs1fAlkD1sTIpZVwFyyiJA+39PraWnsPcs+tcedTuj7ElRHW6QY3xeHR1gX5l6IbqZkwCJ77AHjc3uMv1E0/pa/TCNHonMKQyF4AG9/9w8zkx/MZlaJuu7OYBwhrPjPfi8P5JokWAA+qh+SEAZTOMjntme0dODSt7ea5cHWLwkWZkohODTZAsAxomZS0RWTG2qvqYCSXgDZ0LoQd0Rb78eVvfgZ1drVstw9PHMcZjr92PrkY3hJt9Irg64ct5M8qc5WnXNVEVur6NVcJbwsBUVkxEA32rZfdW8S7phWs24Nyn7zvNUCm0+YFBOv8KnFhaVUnSPcJZFDb9lmQbtoRFQ/yWDqrqA=
