name: Update web

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  deploy-web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          npm ci
          cd web
          npm ci
          cd ..

      # Runs a single command using the runners shell
      - name: Build
        run: |
          cd web
          npm run build
          cd ..

      # Runs a single command using the runners shell
      - name: Deploy
        env:
          NEOCITIES_USER: ${{ secrets.NEOCITIES_USER }}
          NEOCITIES_PASS: ${{ secrets.NEOCITIES_PASS }}
        run: npm run ci-deploy-web
